[workspace]
[package]
name = "html-page"
version = "1906.925289.572444"
edition = "2021"
authors = [
  "Lars Wirzenius <liw@liw.fi>",
]
license = "MIT-0"
description = "Represent HTML using Rust types"
repository = "https://gitlab.com/larswirzenius/html-page"

[dependencies]
html-escape = "0.2.13"
