[v1]
"gnostr_gnit 1895.933117.678085 (path+file:///Users/Shared/gnostr-org/.github/gnostr/gnit)" = [
    "daemonize",
    "gnostr-ssh",
]
"gnostr_js 1894.934224.276199 (path+file:///Users/Shared/gnostr-org/.github/gnostr/js)" = [
    "embedded_js",
    "embedded_main_js",
    "gnostr-gnit",
    "gnostr-web",
    "gnostr_js",
    "warp_filters",
    "websockets_chat",
]
