version: '3.8'
services:
  gnostr-node:
    build: .
    volumes: ["gnostr_data:/data"]
  nginx:
    image: nginx:alpine
    ports: ["80:80"]
    volumes: ["./nginx.conf:/etc/nginx/nginx.conf:ro"]
  tor:
    image: goldy/tor-hidden-service
    links: ["nginx"]
    volumes: ["tor_keys:/var/lib/tor/hidden_service/"]
volumes:
  gnostr_data:
  tor_keys:
