[package]
name = "dev_mode"
version = "0.1.0"
edition = "2024"

[dependencies]
damus_js = { path = "../.." }
futures-util = "0.3.31"
handlebars = "6.3.2"
lazy_static = "1.5.0"
pretty_env_logger = "0.5.0"
serde = "1.0.219"
serde_json = "1.0.140"
sha2 = "0.10.8"
tiny_http = "0.12.0"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1.17"
warp = "0.3"


[dev-dependencies]
damus_js = { path = "../.." }
