wss://relay.damus.io
wss://nos.lol
wss://relay.nostr.band
wss://nostr-pub.wellorder.net
wss://relay.primal.net
wss://nostr.bitcoiner.social
wss://atlas.nostr.land
wss://relay.mostr.pub
wss://purplepag.es
wss://nostr.wine
