[package]
name = "gnostr-asyncgit"
version = "1894.934217.283628"
authors = [
    "gnostr <admin@gnostr.org>",
    "extrawurst <mail@rusticorn.com>",
    "altsem <altem@unknown.com>",
]
edition = "2021"
description = "gnostr:fork of asyncgit"
homepage = "https://github.com/gnostr-org/gnostr"
repository = "https://github.com/gnostr-org/gnostr"
readme = "README.md"
license = "MIT"
categories = ["concurrency", "asynchronous"]
keywords = ["git"]

[lib]
name = "gnostr_asyncgit"
path = "src/lib.rs"

[features]
default = ["trace-libgit"]
trace-libgit = []
vendor-openssl = ["openssl-sys"]

[dependencies]
arboard = { version = "3.4.0", default-features = false, features = [
    "windows-sys",
] }
#anyhow = "1.0"
bitflags = "2"
chrono = "0.4.40"
clap = { version = "4.5.34", features = ["derive"] }
crossbeam-channel = "0.5"
crossterm = "0.28.1"
dirs = "5.0.1"
easy-cast = "0.5"
etcetera = "0.10.0"
figment = { version = "0.10.19", features = ["toml"] }
fuzzy-matcher = "0.3"
git-version = "0.3.9"
git2 = { version = "^0.20", default-features = false }
git2-hooks = { package = "gnostr-git2-hooks", path = "../git2-hooks", version = "1895.933117.678085" }
itertools = "0.14.0"
log = "0.4"
# log = "0.4.27"
nom = "7.1.3"
nostr-sdk = { version = "0.37", features = ["all-nips"] }
#nostr-sdk = "0.37.0"
notify = "7.0.0"
# git2 = { path = "../../extern/git2-rs", features = ["vendored-openssl"]}
# git2 = { git="https://github.com/extrawurst/git2-rs.git", rev="fc13dcc", features = ["vendored-openssl"]}
# pinning to vendored openssl, using the git2 feature this gets lost with new resolver
openssl-sys = { version = '0.9', optional = true }
ratatui = { version = "0.29.0", features = ["serde"] }
rayon = "1.10"
rayon-core = "1.12"
regex = "1.11.1"
scopetime = { package = "gnostr-scopetime", path = "../scopetime", version = "1895.933117.678085" }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
# serde = { version = "1.0.219", features = ["derive"] }
similar = { version = "2.7.0", features = ["unicode", "inline"] }
simple-logging = "2.0.2"
ssh-key = { version = "0.6.6", features = ["crypto", "encryption"] }
strip-ansi-escapes = "0.2.1"
thiserror = "1.0"
toml = "0.8.20"
tree-sitter = "0.20.10"
tree-sitter-grammar-repository = { version = "1895.933117.678085", path = "../js/tree-sitter-grammar-repository" }
tree-sitter-highlight = "0.20.1"
tui-prompts = "0.5.0"
unicode-segmentation = "1.12.0"
unicode-truncate = "1.0"
url = "2.2.2"

## [[bench]]
## name = "show"
## harness = false

[dev-dependencies]
#cargo-insta = "1.43.1"
criterion = "0.5.1"
env_logger = "0.11"
insta = "1.42.2"
invalidstring = { package = "gnostr-invalidstring", path = "../invalidstring", version = "1895.933117.678085" }
pretty_assertions = "1.4"
serial_test = "3.1"
# pretty_assertions = "1.4.0"
temp-dir = "0.1.13"
tempfile = "3"
unicode-width = "0.2.0"

[profile.release]
strip = true
