[package]
name = "gnostr-extensions"
version = "1894.934224.276199"
description = "gostr-relay extensions."
edition = "2021"
authors = ["Arron zhang <arronzhang@me.com>", "gnostr <admin@gnostr.org>"]
readme = "README.md"
homepage = "https://gnostr.org"
repository = "https://github.com/gnostr-org/gnostr.git"
license = "MIT"
keywords = ["nostr", "nostr-relay", "server", "gnostr", "git"]
categories = ["network-programming", "web-programming"]

[features]
default = ["metrics", "rate_limiter", "count"]
search = ["gnostr-relay/search"]
metrics = ["metrics-exporter-prometheus", "metrics-util"]
rate_limiter = ["governor"]
count = []

[dependencies]
actix = "0.13.5"
actix-web = "4.9.0" ## part of gnostr tokio runtime conflict
gnostr-relay = { version = "1894.934224.276199", path = "..", features = [
  "search",
] }
governor = { version = "0.6.3", optional = true }

metrics = "0.23.0"
metrics-exporter-prometheus = { version = "0.15.3", optional = true, default-features = false, features = [
  "push-gateway",
] }
metrics-util = { version = "0.17.0", optional = true }
parking_lot = "0.12.3"
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
tracing = "0.1.40"
uuid = { version = "1.10.0", features = ["v4", "fast-rng"] }

[dev-dependencies]
actix-rt = "2.10.0" ## part of gnostr tokio runtime conflict
actix-test = "0.1.5"
actix-web-actors = "4.3.1"
anyhow = "1.0.86"
bytes = "1.7.1"
futures-util = "0.3.30"
temp-env = "0.3.6"
tempfile = "3.12.0"
tracing-subscriber = "0.3.18"
