name: nix_develop_matrix
on:
  schedule:
    - cron: '0 0 * * *' # run once a day
  pull_request:
    branches:
      - 'ma**'
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - 'ma**'

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  nix_develop_matrix:
    env:
      NGIT: "ngit"
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
        rustup: [stable, nightly]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix develop --command rustup default ${{ matrix.rustup }}
    - run: nix develop --command rustup show
    - run: nix develop --command cargo clippy
    - run: nix develop --command cargo fmt --all -- --check
    - run: nix develop --command cargo test -- --nocapture
