[package]
name = "html-page"
version = "1894.934224.276199"
edition = "2021"
authors = ["Lars Wirzenius <liw@liw.fi>"]
license = "MIT-0"
description = "Represent HTML using Rust types"
repository = "https://gitlab.com/larswirzenius/html-page"
[workspace]

[dependencies]
html-escape = "0.2.13"
